name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Atualiza a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar animação da cobrinha
        id: generate_snake
        uses: Platane/snk@v3
        with:
          github_user_name: Machadomq
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit e push da cobrinha para a branch `main`
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Atualizando animação da cobrinha" || echo "Nenhuma alteração para commit"
          git push origin main || echo "Nenhuma alteração para push"


